### ISSUE TITLE
Increase horizontal breakpoint

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/documentation#1006]
or hide the page-local menu until a wider viewport (1200+) or something.

The new layout of the doc (especially technical) made it 3 columns starting at 992px wide. That is way too low, at that width the two menu colums basically take as much space (each) as there is left for the body text:
![Screen Shot 2021-06-01 at 11 57 33](https://user-images.githubusercontent.com/7571158/120305002-92fd6c00-c2d0-11eb-958f-232ddca9e2e6.png)

This is an issue for me because I currently use a widescreen display split in thirds, each third is ~1150 pixels wide, which is wide enough to trigger the 3-columns layout but not wide enough to really be usable then:
![Screenshot from 2021-06-01 12-00-07](https://user-images.githubusercontent.com/7571158/120305381-f8e9f380-c2d0-11eb-8b65-9c67dbce8948.png)

Because of the size of the side columns, I'm not convinced it's a good idea until way later, possibly 1440 or even 1600-wide viewports: the `nav` column is 400px wide (including the 3 rem left padding) and the local toc is 25% wide (+ 3 rem ~ 50px), plus the body content has 3 rem padding on each side (so ~90 px).

This means the body content only has x * 0.75 - (350 + 45*4)px available.

At 1200px viewport that's 370px, at 1440 it's 550px, at 1600 it's 670, finally exceeding the 640x480 displays of yore.

Also the per-document menu should probably have a fixed size, there is *no reason* to make it 25% wide. And paddings of 3rem everywhere seems way excessive.

**Comment by AntoineVDV** [comment]
@edi-odoo

**Comment by edi-odoo** [comment]
Thank you for your feedback @xmo-odoo , I'm looking into it.
Paddings are large for better readability, as there is a lot of text. They are reduced on mobile. 
There _is a reason_ to make it 25% large, and that is a design reason: the alignment with the dropdown elements in the header.
Your widescreen display cut into thirds is _just_ under the breakpoint. When testing I don't usually cut my screen into thirds, I check that the layout works on most used resolutions:
(desktop)
1366x768 (22.98%)
1920x1080 (20.7%)
1536x864 (7.92%)
1440x900 (7.23%)
1280x720 (4.46%)

(mobile)
360x640 (18.7%)
375x667 (7.34%)
414x896 (6.76%)
360x780 (5.31%)
375x812 (5.01%)
768x1024 (51.43%)

(tablet)
1280x800 (7.28%)
800x1280 (5.26%)
601x962 (4.32%)
962x601 (2.99%)

But I'll make sure to test it properly next time.

**Comment by xmo-odoo** [comment]
> When testing I don't usually cut my screen into thirds

Well sure but the display I have at home is 3440x1440, that's a bit too wide for pretty much everything so depending on the task I tend to use it in 2/3 1/3, 1/3 1/3 1/3, or 1/4 1/2 1/4.

1/4 is 860px so the doc' switches to mobile / single column which works fine, and 1/2 is 1720 which is more than wide enough for the 3 column layout, but 1/3 is just a bit too narrow... and is the main layout I use :D

**Comment by edi-odoo** [comment]
If you turn your display 90° that's a perfect width :D But more seriously, I'll put in an alternate behaviour for esoteric screen resolutions when I have a moment.

**Comment by edi-odoo** [comment]
Closed with #1014
