### ISSUE TITLE
abstract_controller missing - odoo 17 documentation

### ISSUE THREAD

**Issue by simpit-pestalozzi** [odoo/documentation#10676]
on page [View architectures](https://www.odoo.com/documentation/17.0/developer/reference/user_interface/view_architectures.html#reference-view-architectures-list)

the link to [AbstractController](https://www.odoo.com/documentation/17.0/developer/reference/user_interface/%7BGITHUB_PATH%7D/addons/web/static/src/js/views/abstract_controller.js)

leads to an error page
404 Not Found
nginx

![image](https://github.com/user-attachments/assets/7a136eea-69ea-4460-9aec-6f708b03361d)

**Comment by AntoineVDV** [comment]
Hello @simpit-pestalozzi, thanks for reporting this. The code the link was referring to has been moved [here](https://github.com/odoo/odoo/blob/17.0/addons/web/static/src/views/view_hook.js#L56), but it's not relevant in this documentation, so I will remove it with #10729.

**Comment by simpit-pestalozzi** [comment]
OK! Thanks for your quick reply @AntoineVDV 😊
