### ISSUE TITLE
Translation of documentation to pt_BR

### ISSUE THREAD

**Issue by wevertoncampospro** [odoo/documentation#10985]
**Subject:** Solution Request for Documentation Translation Problem on the Odoo website

Dear,

I would like to report a problem related to the translation of documentation into Brazilian Portuguese (pt_BR) on the Odoo website. When accessing the documentation page, the language selection functionality is not working as expected, preventing the content in Portuguese from being viewed.

**Problem Description:**

**Problem:** When accessing the mentioned page and selecting the language for "PT" (Brazilian Portuguese), the content is not translated, remaining in the original language (usually English).

**Impact:** This flaw makes access to information difficult for users who need documentation in Portuguese, generating confusion and possible errors in the interpretation of the instructions contained in the material.
Steps to Reproduce the Problem:

**Access the documentation page at the link provided:** 
https://www.odoo.com/documentation/saas-17.4/pt_BR/applications/finance/accounting.html.

Try changing the language to "PT" using the language selector available on the interface.
Please note that despite the selection, the content continues to be displayed in the original language.

**Expectation:**

We hope that, when selecting the language for "PT", the page content will be displayed in Brazilian Portuguese (pt_BR) correctly and completely.

**Request:**

I request that the translation functionality into Brazilian Portuguese be investigated and corrected, ensuring that users can access documentation in their native language, which is crucial for correctly understanding the information. I am also willing to research with the community how to carry out this work in the best way possible.

**Comment by xpl-odoo** [comment]
Hello @wevertoncampospro 
Odoo doesn't maintain translations of the documentation for intermediary versions.
We recommend that you use the latest major version instead (17.0 here) for translated content.
In your case, [https://www.odoo.com/documentation/17.0/pt_BR/applications/finance/accounting.html](https://www.odoo.com/documentation/17.0/pt_BR/applications/finance/accounting.html).
