### ISSUE TITLE
Fix Mexico doc module names

### ISSUE THREAD

**Issue by JPML94** [odoo/documentation#1106]
Hello.

In v14 the module l10n_mx_edi_external_trade does not exist and the documentation specifies to install it.

Might be good to add a warning/note about the creation of l10n_mx_edi_extended for v14.

cc. @vbe-odoo

**Comment by vbe-odoo** [comment]
Hi @JPML94 agree, there are some modules/apps that should be removed from the DOC in MX.
Thanks for the feedback!
Best

**Comment by jcs-odoo** [comment]
I close this issue as it is acknowledged by @vbe-odoo .

(Let me know if you need help updating the content, Valentino :) )

**Comment by vbe-odoo** [comment]
Hi @jcs-odoo thanks for closing this PR :)
This was already updated in the DOC.
Thanks!
