### ISSUE TITLE
Modules list for Mexican accounting in V14 is out of date

### ISSUE THREAD

**Issue by raf-odoo** [odoo/documentation#1112]
In https://www.odoo.com/documentation/14.0/applications/finance/accounting/fiscal_localizations/localizations/mexico.html?highlight=coupon#modules , the module `l10n_mx_edi_sale_coupon` is mentioned, which doesn't exist in V14. Neither do `l10n_mx_edi_external_trade`, `l10n_mx_edi_customs`, `l10n_mx_edi_payment_bank` and `l10n_mx_tax_cash_basis`. `l10n_mx_edi_landing` still exists. I'll make a PR to remove the entire optional modules section. This issue is so that the modules list in the Mexican documentation gets reviewed and updated where needed after that.

**Comment by raf-odoo** [comment]
PR: https://github.com/odoo/documentation/pull/1113

**Comment by vbe-odoo** [comment]
Hi @raf-odoo I will review PR #1113 and give you my feedback there.
Thanks
