### ISSUE TITLE
Server Framework 101, Basic views links to tree example

### ISSUE THREAD

**Issue by RoelAdriaans** [odoo/documentation#11197]
In the basic views, tree is replaced by list. But the example links to an old commit, where tree is still used.

Offending line: 
https://github.com/odoo/documentation/blob/a2af035da6e31827ca4d5fcccbb6e61bcd50cb6b/content/developer/tutorials/server_framework_101/06_basicviews.rst?plain=1#L47

**Comment by AntoineVDV** [comment]
Hi @RoelAdriaans, thanks for the notice! I'm closing the issue because the Server Framework 101 tutorial is being completely rewritten, and the example link will soon be removed.
