### ISSUE TITLE
The video link mentioned was not found.

### ISSUE THREAD

**Issue by syntaxter** [odoo/documentation#11474]
https://github.com/odoo/documentation/blob/5453741f0ccef88746449a9af08d1b0e1e012392/content/developer/tutorials/server_framework_101/02_newapp.rst?plain=1#L38

**Comment by xpl-odoo** [comment]
Hello @syntaxter ! Thanks for the feedback.

@Feyensv it seems this content originates from #964. While d0c2cb1 was co-authored by multiple people, you might still know if the video was ever recorded? Or should we remove lines 38-40?

**Comment by AntoineVDV** [comment]
Hi @syntaxter, I'm currently rewriting the tutorial and have already removed this mention of the video. So we can keep it a little while longer until the new tutorial content is ready ;)
