### ISSUE TITLE
Inaccessible link in payment terms documentation

### ISSUE THREAD

**Issue by raf-odoo** [odoo/documentation#1342]
The [Odoo learn](https://www.odoo.com/r/fpv) link about T&C and Payment terms at the very bottom of https://www.odoo.com/documentation/15.0/applications/finance/accounting/receivables/customer_invoices/payment_terms.html returns a 403, both when logged in and when not.

Link in source: https://github.com/odoo/documentation/blame/40afc9d9f06db5a2fe75c6f2458102f45510ae37/content/applications/finance/accounting/receivables/customer_invoices/payment_terms.rst#L118 .

**Comment by jcs-odoo** [comment]
Hello @raf-odoo 
Thanks for reporting this.

It seems someone must have unpublished the page on our eLearning platform. It's very strange. Anyway, it's back online :)
