### ISSUE TITLE
Translating String Literals in JavaScript

### ISSUE THREAD

**Issue by 0b11001111** [odoo/documentation#1676]
I spent the entire day to figure out why my translations for JS string literals did not show up on the website.
Turns out that my addon explicitly had to register for that by inheriting `ir.http` and overwriting `_get_translation_frontend_modules_name` to include itself.

There are plenty of posts on the web of people that seem to have the same issue, some of them years old.
If my solution follows the idiomatic way, I'd volunteer to make a PR extending the [docs](https://www.odoo.com/documentation/14.0/developer/misc/i18n/translations.html) respectively.

Otherwise please add a note to the respective section that translations won't become active on their own...

**Comment by mart-e** [comment]
Note that if your module starts with `website`, you don't need to (and this is the convention we usually have, `website_sale`, `website_event`,...)
But sure to add more info in the documentation :)

**Comment by 0b11001111** [comment]
Done, see #1710

Just out of curiosity: are there other addon prefixes that cause special behaviour? Like `theme_*`?
