### ISSUE TITLE
[V15] - Inverse function tutorial example not triggering when changing deadline

### ISSUE THREAD

**Issue by rmazzine** [odoo/documentation#1837]
Hello :)

First, congratulations for this project, I loved it!

I am following the tutorial, and in the exercise to [implement the inverse function](https://www.odoo.com/documentation/15.0/developer/howtos/rdtraining/09_compute_onchange.html#inverse-function), I did the instructed functions:

```python
date_deadline = fields.Date(compute='_compute_date_deadline', inverse='_inverse_date_deadline')

@api.depends('validity')
def _compute_date_deadline(self):
    for record in self:
        if type(record.create_date) is not bool:
            record.date_deadline = fields.Date.add(record.create_date, days=record.validity)
        else:
            record.date_deadline = fields.Date.add(fields.Datetime.today(), days=record.validity)

def _inverse_date_deadline(self):
    for record in self:
        if type(record.create_date) is not bool:
            record.validity = (record.date_deadline - record.create_date.date()).days
        else:
            record.validity = (record.date_deadline - fields.Datetime.today().date()).days
```

although the `_compute_date_deadline` function worked perfectly, the `_inverse_date_deadline` was not being trigged when I changed the date on the calendar.

I found a related problem (https://github.com/odoo/odoo/issues/23891), where the solutions was to use the `api.onchange` (listeining the `date_deadline` field) decorator on the `_inverse_date_deadline` function. Then adding:

```python
@api.onchange('date_deadline')
    def _inverse_date_deadline(self):
        ...
```

After doing that, the inverse function worked and the number of days was calculated automatically. Maybe there's some error in my code, but I didn't find anything wrong.

Feel free to ask for more information/details.

Best,

**Comment by rmazzine** [comment]
Realized now that the inverse is not triggered on-the-fly, but only after the record is edited and saved!

Therefore, it's actually working correctly!

**Comment by aphelei** [comment]
```python
@api.onchange("date_deadline")
    def _onchange_date_deadline(self):
        self.validity = (self.date_deadline - self.date_created).days
```

it's not in the tutorial but this works 
edit: it is, it's the next thing in the tutorial u-u
