### ISSUE TITLE
[V15] - Probable documentation mistake (Advanced B)

### ISSUE THREAD

**Issue by rmazzine** [odoo/documentation#1861]
Hello!

I think there's a small mistake on[ Advanced B documentation](https://www.odoo.com/documentation/15.0/developer/howtos/rdtraining/B_acl_irrules.html).

On the section `Access Rights`, below the groups table, there's a text:

> A user with the groups A and C will be able to do anything but delete the object while one with B and C will be able to read or update, **but not search or read**.

I think it would be: **but not create or delete**

Best regards,

**Comment by AntoineVDV** [comment]
Hi, this issue will be fixed tomorrow in all the concerned versions. Thank you for your contribution :)
