### ISSUE TITLE
can installl libsass==0.18.0 on mac 12.3.1

### ISSUE THREAD

**Issue by jeffery9** [odoo/documentation#2003]
it raise compiling error

```
      ld: library not found for -lc++
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command 'clang++' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> libsass

```

**Comment by jeffery9** [comment]
why not use recently version?

**Comment by AntoineVDV** [comment]
Hello, the versions pinned in the requirements are chosen to be compatible with Odoo's requirements but they are not absolutely mandatory. If you wish, you can use another version than that pinned in the requirements. However, please note that we only support building the documentation on Unix and will therefore not adapt the requirements to be compatible with any OS.
