### ISSUE TITLE
MRP : Access the work order from multiple users instead of starting the work order only once.

### ISSUE THREAD

**Issue by odooaktiv** [odoo/documentation#2150]
**Impacted versions:**
14.0

**Steps to reproduce:**

  Create a MO with work orders
  Confirm the MO
  Under the tab Work Orders,> click on the button the work order can have only one timer started

**Current behavior:**
  start the work order only once from a single user.

**Expected behavior:**
 If the work order already has a timer running, another user can start and Done the work orders simultaneously. 

**Video/Screenshot link:**
https://www.awesomescreenshot.com/video/9317381?key=91d634a535c7dfe03c4e17a673cefcfa

Support ticket number submitted via odoo.com/help (optional):

**Comment by weka-odoo** [comment]
@odooaktiv Hi there! Thanks for your comment. Just to clarify, is there a specific piece of documentation that you'd like to apply this change to?

**Comment by odooaktiv** [comment]
@weka-odoo 
Before a certain commit in v14 of Odoo mrp module, it was possible that multiple users could work on the same workorder by using the timer feature.

As of now, this facility is disabled by adding a condition that only allows a single user to start the timer on work order.

We are planning to add a PR against this issue, so that we can make the multi-user timer configurable under the config settings.

**Comment by odooaktiv** [comment]
Odoo has again enabled this. Closing this issue as of now.
