### ISSUE TITLE
Add option to prevent creation of `__pycache__` directories during development

### ISSUE THREAD

**Issue by AaronBeaudoin** [odoo/documentation#2198]
I thought that launching Odoo with `python3 -B /usr/bin/odoo` would prevent the creation of `__pycache__/` directories in my custom addons directory, but it doesn't seem to have any effect. I still end up with `__pycache__/` directories in all of my custom addon directories during development. The only thing I can think of is that Odoo must be doing something internally that causes them to still be created.

_The reason I want to do this is because when I switch branches in Git while working in my custom addons directory, directories for addons from the branch I just switch **away from** stick around because of the untracked `__pycache__/` directories inside of them. Please be aware that **adding `__pycache__/` to `.gitignore` is not the solution to this problem**. The key is that I need the `__pycache__/` directories to never be created in the first place, so that when I switch branches, directories for addons from the branch I just switched away disappear like expected because **all files** inside of them are tracked._

**Comment by Julien00859** [comment]
We don't do anything related to `__pycache__/`, `*.pyc` or the `-B` cli option. On my own computer, starting odoo-bin using the python's `-B` option, no `__pycache__` was created.

	# No __pycache__
	~/Odoo $ ls custo/julien/
	controller.py  data  __init__.py  ir.model.access.csv  __manifest__.py  model.py  static  view.xml

	# Run with -B
	~/Odoo $ python3 -B community/odoo-bin --log-level=warn --stop-after-init -c config.cfg -d 'odoo-master-test' 

	# Still no __pycache__
	~/Odoo $ ls custo/julien/
	controller.py  data  __init__.py  ir.model.access.csv  __manifest__.py  model.py  static  view.xml

	# Run without -B
	~/Odoo $ python3 community/odoo-bin --log-level=warn --stop-after-init -d 'odoo-master-test'

	# __pycache__ created
	~/Odoo $ ls custo/julien/
	controller.py  data  __init__.py  ir.model.access.csv  __manifest__.py  model.py  __pycache__  static  view.xml

**Comment by AaronBeaudoin** [comment]
So it looks like the problem is that although I initially start the server with `python3 -B` and no `__pycache__/` directories are generated, if I ran the server with `--dev reload` then the `__pycache__/` directories get generated after a file change. I assume this is because whatever process is restarting the server does not call `python3` with the `-B` argument as desired.

Any solution to this?

**Comment by Julien00859** [comment]
Don't use --dev reload :grimacing:

**Comment by AaronBeaudoin** [comment]
Haha, yeah that'd be an easy fix, but I'd lose a lot too.

It'd be nice if during development I could have the server refresh automatically _**and**_ keep my directories clean.

**Comment by Julien00859** [comment]
It is not possible we reset the -B when reexecuting the server, the information is lost before getting into the program. What you can do instead is run odoo-bin with the PYTHONDONTWRITEBYTECODE=1 environment variable.
