### ISSUE TITLE
need better theme to display the struct of documents

### ISSUE THREAD

**Issue by jeffery9** [odoo/documentation#2428]
for example,  <dt>  need more indent space for better visual effect.

![image](https://user-images.githubusercontent.com/1404460/177994475-dc3b96b1-d684-40d4-8f06-b01506ed69bc.png)

very hard to make sense that  field is the upper layer.

**Comment by jcs-odoo** [comment]
Hello @jeffery9 ,

This has been improved already. Can you try a hard refresh of the page (ctrl+shift+r)?
It should look like this:
![image](https://user-images.githubusercontent.com/46810843/178005440-47e08a11-2d99-4746-93e9-e813d34a886c.png)

Have a good weekend :)
