### ISSUE TITLE
The "Advanced B: ACL and Record Rules" inconsistency

### ISSUE THREAD

**Issue by horodchukanton** [odoo/documentation#2488]
In the Tutorial Chapter "Advanced B: ACL and Record Rules", there's a mention of a `bypass.py` script that is not shown, mentioned, and present in the distribution.

https://github.com/odoo/documentation/blame/15.0/content/developer/howtos/rdtraining/B_acl_irrules.rst#L341

Is this a typo or just a script that was intended but not included in the tutorial?

**Comment by AntoineVDV** [comment]
Hi @horodchukanton, it's indeed not present anywhere. @nim-odoo @jpp-odoo does it ring a bell for you guys?

**Comment by nim-odoo** [comment]
I'm 99% I never wrote that.

**Comment by AntoineVDV** [comment]
The mention of the script was removed with https://github.com/odoo/documentation/pull/2518 :)
