### ISSUE TITLE
Restore previous version of a webpage

### ISSUE THREAD

**Issue by VinceGolo** [odoo/documentation#2585]
Hi,
For some reason I have lost my entire webpage that I have created on : https://pro-golookall.odoo.com/ and I didn't do any backup. I know get a 404 message.
This happened just 30 minutes ago. Does anyone know how I can restore the last version of my webpage ?

In advance thank you very much for your help and reply.

Vincent

**Comment by jcs-odoo** [comment]
Hello @VinceGolo 
Sorry to read this! Please create a ticket on www.odoo.com/help to contact Odoo's support.

For what I see, only the homepage is affected and the other pages are still available from the menu. Could you check if your page is still listed in the pages? Maybe you unpublished it by mistake?

Good luck :-)

Jonathan

**Comment by VinceGolo** [comment]
Hi Jonathan,
Thanks a lot for your answer. I did contact (http://www.odoo.com/help) and they did reply.
For some raison the URL address that was recorded under "Pages" of the website was modified which created the bug.
The issue is now resolved.
Again thanks for your helps.
Best
Vincent
