### ISSUE TITLE
[16.0] install doc for nginx: add map $http_upgrade $connection_upgrade

### ISSUE THREAD

**Issue by jcdrubay** [odoo/documentation#2750]
I think you should add this part to the nginx sample configuration as the current one is not working without this:

```
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
```

https://www.nginx.com/blog/websocket-nginx/

**Comment by jcs-odoo** [comment]
Hi @jcdrubay , thank you for your feedback.

Hello @d-fence Unless I'm mistaken, I think this is for you :)

**Comment by zeroheure** [comment]
I disagree. My Odoo 16 install works without that. AFAIK WebSocket is only required for the chat box.

**Comment by jcdrubay** [comment]
Thanks for the follow-up @zeroheure 

Isn't the chatbox installed/available in most of odoo installations with the module mail?

I tried without that nginx configuration and it seems to work well now. So maybe it was related to a defect that was fixed.

Maybe this configuration is not required anymore after 
https://github.com/odoo/odoo/commit/a26c8aa18ad6

I will monitor more in coming days.

**Comment by zeroheure** [comment]
> Isn't the chatbox installed/available in most of odoo installations with the module mail?

Sorry, I was talking about the website chatbox, which use WebSocket now, instead of longpolling in previous versions.

**Comment by Julien00859** [comment]
The issue was raised internally by other developers, I'm +1 we add it to the example nginx snippet

**Comment by Julien00859** [comment]
#2807
