### ISSUE TITLE
compose: "loading" screen

### ISSUE THREAD

**Issue by smokeyrd** [odoo/documentation#2804]
Odoo: 15.0.20221010
Plugin: Current on google scripts: Last modified Feb 21, 2022

When composing an email, I get a "loading" screen that never goes away, but I can hit escape or click on the X to exit the window.
![image](https://user-images.githubusercontent.com/2348179/194948696-ec0cbd7c-8108-40c4-bf28-a20244c6860d.png)

Issue presented mid august. Exact date unknown.

Confirmed on following browsers:
Brave: v1.44.108
Chrome: 106.0.5249.103
Edge: 106.0.1370.37
Firefox: 105.0.3

**Comment by smokeyrd** [comment]
ah, fail... I didn't spot the change from the gmail plugin thread to the odoo documentation thread. Sorry folks. Closing out and marking not planned. My bad.

**Comment by AntoineVDV** [comment]
No problem! :)
