### ISSUE TITLE
Cash Rounding: Add suggestions for Gain & Loss accounts 

### ISSUE THREAD

**Issue by itpetarabia** [odoo/documentation#2841]
In this file, it would be nice to add suggestions for existing accounts that we could use. Some folks might use Product Sales, or create their own.
content/applications/finance/accounting/receivables/customer_invoices/cash_rounding.rst

**Comment by chiaraprattico** [comment]
I checked and it seems like there are no accounts concerned in the cash rounding, the page still needs to be updated so I'll create a new PR for this in the future, thanks
