### ISSUE TITLE
Automated Inventory Valuation samples are very confusing

### ISSUE THREAD

**Issue by zeroheure** [odoo/documentation#2842]
The **Automated Inventory Valuation** samples are very confusing.
See `/applications/inventory_and_mrp/inventory/management/reporting/inventory_valuation_config.html` [url](https://www.odoo.com/documentation/16.0/applications/inventory_and_mrp/inventory/management/reporting/inventory_valuation_config.html)

Sound like there is a long time typo in `documentation/static/js/coa-valuation-continental.js` [url](https://github.com/odoo/documentation/tree/master/static/js/coa-valuation-continental.js).

The **Automated Inventory Valuation / Continental Accounting** part shows both _Vendor Invoice_ and _Vendor Goods Reception_ while, as I understand it, it should be _Supplier Invoice_ and _Vendor Goods Reception_, isn't it ?

Also the PO abreviation, should be changed in Purchase Order to ease understanding, because the js file is never translated.

**Comment by StraubCreative** [comment]
Update: Items raised in this issue, where applicable, are being addressed on #3242.

**Comment by zeroheure** [comment]
Sorry, but no, not at all. I've carefully checked the whole text, and I've seen only longest line breaks, additions of one comma and one "the" word, and some uppercased words.
I have no doubt that grammar was checked.

But my report was about the confusing samples in the "Automated Inventory Valuation" paragraph. Those samples are all in the `documentation/static/js/coa-valuation-continental.js` file, which was left untouch (in this commit).  If there is no errors in these samples, I think that the corresponding text is ambiguous. May be the text is a bit terse and could be expanded a little ?

**Comment by StraubCreative** [comment]
Ah ok, that makes sense. Thanks for clarifying further @zeroheure, we'll take another look 👀

**Comment by StraubCreative** [comment]
Hi @zeroheure 

We did a complete doc rewrite on #3242 which went through multiple content and technical reviews and was approved.
The doc should be much easier to understand now.

If you have any more issues you'd like to raise regarding this doc or other articles please feel free to do so on a new PR.
Thanks again for bringing to our attention and pushing for clarity 🙂 

cc: @brse-odoo

**Comment by zeroheure** [comment]
Hi @StraubCreative 
I've read it. Fantastic ! Your and the team did a very good job.
