### ISSUE TITLE
[16] User Docs -> Websites -> Live Chat ... does not mention Chat Bots (new feature)

### ISSUE THREAD

**Issue by ray-odoo** [odoo/documentation#3120]
https://www.odoo.com/documentation/16.0/applications/websites/livechat/overview/get_started.html

There is no coverage of Chat Bots

Content about this feature can be found at https://www.youtube.com/watch?v=l7wro6LhAq0

**Comment by AntoineVDV** [comment]
@odoo/website-doc-review

**Comment by toaa-odoo** [comment]
@ray-odoo Thanks for the feedback! eCommerce/Website is undergoing a massive documentation overhaul, so the page will be updated at some point. I don't know exactly when, but rest assured it will be done :)
