### ISSUE TITLE
[FIX/IMP] Main/README.md

### ISSUE THREAD

**Issue by RobbiDev** [odoo/documentation#3478]
A small Markdown formatting mistake I found on the 16.0 branch. Nothing major but submitting a Fix/improvement issue to make the readme more organized and professional.

Current 16.0 README.md 
```md
- Make
- A local copy of the [odoo/odoo repository](https://github.com/odoo/odoo) (optional)
```

Suggested Change
```md
- Make A local copy of the [odoo/odoo repository](https://github.com/odoo/odoo) (optional)
```

**Comment by jcs-odoo** [comment]
Hi @RobbiDev ,
Thanks for the feedback and contribution to the documentation :)

In this case, [Make](https://www.gnu.org/software/make/) is a software requirement, not a verb.
"A local copy of..." is a noun group.

Feel free to send more feedback our way, it's always appreciated.
