### ISSUE TITLE
Mail plugin configuration in any on premise environment

### ISSUE THREAD

**Issue by pere-aquarian** [odoo/documentation#3645]
Hi all!

In order to make the mail plugin work in a non sh environment, is necessary to add some instructions missing in [the documentation](https://www.odoo.com/documentation/15.0/applications/productivity/mail_plugins/gmail.html):

- replace all the [odoo.com](https://odoo.com/) references in appsscript.json file (urlFetchWhitelist section) with your domain

It can be done just overwriting the *.odoo.com references or maybe setting the odooUrl or other variable with your domain, what could be more efficient and flexible. 

Thank you!

**Comment by jcs-odoo** [comment]
Hi, @pere-aquarian , thanks for the feedback.

Hi @meng-odoo , I think this is for you :)

**Comment by meng-odoo** [comment]
Added these missing instructions on PR [#3695](https://github.com/odoo/documentation/pull/3695) :)
