### ISSUE TITLE
Missing button in website configuration

### ISSUE THREAD

**Issue by TadeuszKarpinski** [odoo/documentation#4054]
Impacted versions:
16.0
Steps to reproduce:
According to documentation, there should be a button
https://www.odoo.com/documentation/16.0/developer/howtos/themes.html#update-your-theme
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by jcs-odoo** [comment]
Unless I'm mistaken, it's related to the PR https://github.com/odoo/documentation/pull/3047

cc @CVDE-odoo

**Comment by TadeuszKarpinski** [comment]
@jcs-odoo impacted version is 16.0, your PR is 15.0. So... not. It isn't related

**Comment by AntoineVDV** [comment]
PRs merged in 15.0 are automatically applied to 16.0 too, so this issue will indeed be resolved by #3047 ;)
