### ISSUE TITLE
[16] Theme prefix

### ISSUE THREAD

**Issue by imanie383** [odoo/documentation#4767]
By default, the prefix for the themes is "theme_" but in the odoo tutorial 16 it says that the prefix is "website_"

https://www.odoo.com/documentation/16.0/developer/howtos/website_themes/theming.html#global
![image](https://github.com/odoo/documentation/assets/35231827/4ceab097-edf8-45dd-a677-d38a6dfbcb4a)

but in the code the prefix evaluated in odoo 16 is `theme_`
https://github.com/odoo/odoo/blob/a65dda25b95fa904879ca8e7b3309f00ed21fbbf/addons/website/models/ir_module_module.py#L83

And the default theme is named theme_default
https://github.com/odoo/odoo/tree/16.0/addons/theme_default
![image](https://github.com/odoo/documentation/assets/35231827/57331747-f619-4dc9-b2ca-785d0e60921d)

**Comment by xpl-odoo** [comment]
Thanks for the feedback @imanie383 !
@CVDE-odoo could you have a look?

**Comment by CVDE-odoo** [comment]
Thank you for the feedback @imanie383 @xpl-odoo 

This is because we are creating a module, not an actual theme.
We prefix the module with `website_` because it's linked to the website app.

**Comment by CVDE-odoo** [comment]
I closed this issue. Don't hesitate to reopen it if needed.

**Comment by CVDE-odoo** [comment]
@imanie383 Yes, the themes are modules too. In this case, we can't use "themes" modules as they contain python and won't be usable on Saas. So we have to create "classic" modules to make it work, and we can't use the "theme_" prefix.

**Comment by imanie383** [comment]
FYI: the theme can have Python by example the post_coy
