### ISSUE TITLE
Inconsistent naming of test_model between Getting started Ch.4 and Ch.6

### ISSUE THREAD

**Issue by dispread** [odoo/documentation#5482]
In [Ch.4 - Model fields](https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/04_basicmodel.html#model-fields) we set the model name as `test_model`.

Later [in Ch.6 - Actions](https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/06_firstui.html#actions) we use `test.model` as the name for the model 

If we use the code from Ch.6 with code from previous chapters it throws `Invalid model name 'test.model' in action definition.` and doesn't compile. However changing the xml res_model name to `test_model` resolved the issue.
I am still quite new to this so if I'm wrong lmk.

**Comment by AntoineVDV** [comment]
Hello @dispread, you are correct. The suggested model name was changed with https://github.com/odoo/documentation/pull/5131, but Chapter 6 was omitted. I'll fix that now :)
