### ISSUE TITLE
Support for customizations covered by a maintenance should be included

### ISSUE THREAD

**Issue by erl-odoo** [odoo/documentation#5519]
We had a [support task](https://www.odoo.com/web#id=3463923&menu_id=4720&cids=1&action=333&active_id=1276&model=project.task&view_type=form) that was refused by a colleague to a customer paying maintenance and justified with this line from the documentation:
![image](https://github.com/odoo/documentation/assets/84017456/f14d1c74-ab4b-4728-a3b6-1a04bce8d2b8)
This is indeed confusing because we do offer support for customizations if a maintenance fee based on lines of code is payed with the subscription and it should be clarified.

**Comment by erl-odoo** [comment]
Hello @Feyensv, I pinged you based on the git blame, can I get your input please or redirection to who should deal with this?
Thanks

**Comment by Feyensv** [comment]
The content was moved recently to the help page directly, and the page is planned to be removed from the documentation soon.
The [help](https://www.odoo.com/help) page should be the only reference from now on (and if there is something to change/clarify on it, I believe it should be handled with the support team managers).

**Comment by erl-odoo** [comment]
Thanks, I'll try to figure it out with the support team.
