### ISSUE TITLE
Omission in External API documentation for ODOO 17

### ISSUE THREAD

**Issue by ruti-se** [odoo/documentation#6919]
In 17.0/content/developer/reference/external_api.rst it is not mentioned that the XML API requires 2-factor authentication to be disabled for the account on which the xml-rpc API is invoked (although it seems it must be enabled to generate API keys).

Having it enabled will result in exceptions when trying to connect to odoo, since a cookie td_id is incorrectly assumed to exist.

**Comment by Julien00859** [comment]
2-factors authentication must NOT be disabled, you have to use [API Keys](https://www.odoo.com/documentation/17.0/developer/reference/external_api.html#api-keys) instead

**Comment by Julien00859** [comment]
![image](https://github.com/odoo/documentation/assets/8208953/63e87a7d-59fd-42fa-adf5-e5e9d95cd344)

![image](https://github.com/odoo/documentation/assets/8208953/da2982bb-9743-4918-add3-6ef9027fe88f)


```
~ $ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlrpc.client
>>> common = xmlrpc.client.ServerProxy("http://odoo.localhost/xmlrpc/2/common")
>>> common.version()
{'server_version': '16.0+e', 'server_version_info': [16, 0, 0, 'final', 0, 'e'], 'server_serie': '16.0', 'protocol_version': 1}
>>> uid = common.authenticate('odoo-16.0-test', 'admin', '836c47a615703cf5f52d11dfb1a2d9b160a32927', {})
>>> uid
2
```

**Comment by ruti-se** [comment]
Thanks Julien,

I use API keys.

In actuality it works the other way around, when I enable the two-factor authorization it does not work since code incorrectly assumes the presence of a td_id cookie in the api-call (which cannot logically exist on the first connect call from my machine).

When I disable two-factor authorization it does work, with the following trace:

Failed login using adapter odoo:XML-RPC fault: Traceback (most recent call last):
File "/home/odoo/src/odoo/17.0/odoo/addons/base/controllers/rpc.py", line 150, in xmlrpc_2
response = self._xmlrpc(service)
File "/home/odoo/src/custom/trial/saas_trial/controllers/main.py", line 302, in _xmlrpc
res = super(OdooRPC, self)._xmlrpc(service)
File "/home/odoo/src/odoo/17.0/odoo/addons/base/controllers/rpc.py", line 130, in _xmlrpc
result = dispatch_rpc(service, method, params)
File "/home/odoo/src/odoo/17.0/odoo/http.py", line 388, in dispatch_rpc
return dispatch(method, params)
File "/home/odoo/src/odoo/17.0/odoo/service/common.py", line 56, in dispatch
return g[exp_method_name](https://github.com/faisalsami/odoo-xmlrpc/issues/*params)
File "/home/odoo/src/odoo/17.0/odoo/service/common.py", line 27, in exp_authenticate
return res_users.authenticate(db, login, password, {**user_agent_env, 'interactive': False})
File "/home/odoo/src/odoo/17.0/addons/auth_signup/models/res_users.py", line 129, in authenticate
if env.user._should_alert_new_device():
File "/home/odoo/src/odoo/17.0/addons/auth_totp/models/res_users.py", line 52, in _should_alert_new_device
key = request.httprequest.cookies.get('td_id')
File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 432, in get
obj = instance._get_current_object()
File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 554, in _get_current_object
return self.__local() # type: ignore
File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 226, in _lookup
raise RuntimeError("object unbound")

**Comment by ruti-se** [comment]
For clarification - I do not run through a browser, instead it is running from a backend server using xml-rpc from node.js. Code that does work on older versions of odoo does no longer work on odoo 17, unless disabling 2fa. My guess is that there is a logical error in /home/odoo/src/odoo/17.0/addons/auth_signup/models/res_users.py", line 129. for m2m usecase with API keys.

**Comment by Julien00859** [comment]
Thank you for the complete traceback, I now understand what the problem is. I'm going to have a deeper look.

**Comment by ruti-se** [comment]
Thank you for kindly adressing this issue.
