### ISSUE TITLE
[17.0+e] [SAAS] Wrong documentation for internal transfer

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [odoo/documentation#7206]
New database on odoo.com I have linked both Bank and PayPal accounts with Salt Edge.
I went on the accounting dashboard to register an internal transfer as normal but the internal transfer option doesn't seem to exist any more.
I Checked docs @ https://www.odoo.com/documentation/17.0/applications/finance/accounting/payments/internal_transfers.html to see if its changed but that shows the same as we are used to on self hosted.

Screen shots of both my self hosted (v16) and SaaS (v17).

Odoo 16 Self hosted:
![o16-self-hosted](https://github.com/odoo/documentation/assets/118213587/b42e936d-2967-4b45-a72a-41efe45ac29f)

Odoo 17+e SaaS:
![o17-saas](https://github.com/odoo/documentation/assets/118213587/3ed7594c-2023-4936-9352-b7b46b8d8f26)

**Comment by jcs-odoo** [comment]
Hi @Entrepreneur-AJ 
Thanks for the feedback.

From Odoo 17, you can make internal transfers from any payment form, by checking the "Internal Transfer" box.
<img width="1100" alt="image" src="https://github.com/odoo/documentation/assets/46810843/d63cbd3f-a310-43ea-97ec-0d660ce2bd67">

Hi, @chiaraprattico could you update this doc, and reference this issue in the PR (right side bar), please? Thanks!

**Comment by chiaraprattico** [comment]
Hi, started working on this PR, thanks for the heads up.
