### ISSUE TITLE
Odoo is by default logging to stderr instead of stdout

### ISSUE THREAD

**Issue by kajedot** [odoo/documentation#7210]
Impacted versions: 14.x, 15.x, 16.x, 17.x

Steps to reproduce: 

Run odoo with commands:
`python odoo-bin 2>stderr.txt `
`python odoo-bin 1>stdout.txt`

Current behavior:
File stdout.txt is empty. All log levels (DEBUG and INFO for sure) are logged to stderr. This is the inconsistency with the Odoo [documentation](https://www.odoo.com/documentation/17.0/developer/reference/cli.html?highlight=logging#logging): "By default, Odoo displays all logging of [level](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) info except for workflow logging (warning only), and log output is sent to **stdout**"

Expected behavior:
Assuming there is no mistake in the documentation, Odoo should log every message to the stdout stream (so in my case stdout.txt should be populated). But considering logging module which Odoo is using, which sends everything to stderr, it is a mistake in documentation. 

Disclaimer: 
`1>filename   # Redirect stdout to file "filename."`
`2>filename   # Redirect stderr to file "filename."`
Reference: https://tldp.org/LDP/abs/html/io-redirection.html.

**Comment by Julien00859** [comment]
Indeed, we always only log on stderr, that's the default behavior of the python StreamHandler class that we are using. We should correct the documentation, I'll do it.

https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler 
https://github.com/odoo/odoo/blob/b3b9b2b49ef90d30bcce1e27a4ba0b24f888170c/odoo/netsvc.py#L156
https://github.com/odoo/odoo/blob/b3b9b2b49ef90d30bcce1e27a4ba0b24f888170c/odoo/netsvc.py#L198
