### ISSUE TITLE
Whatsapp on Odoo Community 17

### ISSUE THREAD

**Issue by Olive-harobed** [odoo/documentation#7450]
I went through the documentation and was under the impression that Whatsapp was available on odoo community which I set up on my own instance. I have been looking for the whatsapp module and it is not there. To clarify, is this only available on enterprise? Or is there a step or is it under a different name?

**Comment by AntoineVDV** [comment]
Hi @Olive-harobed, the standard WhatsApp integration is available only with Odoo Enterprise. That should indeed be made clear on the docs; thanks for the heads up!

cc @odoo/whatsapp-doc-review

**Comment by StraubCreative** [comment]
Notices added on #7483, should be all set!
