### ISSUE TITLE
remote: Support for password authentication was removed on August 13, 2021.

### ISSUE THREAD

**Issue by JeromeBotineau** [odoo/documentation#9023]
Hello,

Odoo Sh is intergrated with Github.
In the documentation for Odoo Sh, you explain that you can push from Odoo.sh editor terminal
https://github.com/odoo/documentation/blob/17.0/content/administration/odoo_sh/getting_started/first_module.rst?plain=1#L169-L173

But it doesn't work since August 13, 2021

```sh
git push https HEAD:feature-1
Username for 'https://github.com': JeromeBotineau
Password for 'https://JeromeBotineau@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/my-orga/project-name.git/'
```

**Comment by jcs-odoo** [comment]
@amigrave I think this is for you :)

Hello @JeromeBotineau thanks for the feedback

**Comment by amigrave** [comment]
Hi @JeromeBotineau 

Indeed, this section of the documentation is outdated but a new feature will be released in June that will ease pushing code from a webshell and from the editor as well and will support the multi-user context. The feature will be advertised in the "What's new" widget when released.

@jcs-odoo if you want you can remove this section from the documentation

**Comment by xpl-odoo** [comment]
cc @frps1
