### ISSUE TITLE
Change Screenshot on page https://www.odoo.com/documentation/user/14.0/point_of_sale/payment/six.html

### ISSUE THREAD

**Issue by rjo-odoo** [odoo/documentation#954]
- in V13: display name is "Six without IOT Box"
- in v14: dispay name was shortened for "Six" => when you select this terminal, the field "Six Terminal IP" is automatically visible > Works as expected (without iOT box)
This change needs to be reflected in the documentation.

![v14](https://user-images.githubusercontent.com/61477595/117046445-8f70c800-acc5-11eb-9ed9-bc61e3bcc619.png)
![v13](https://user-images.githubusercontent.com/61477595/117046454-913a8b80-acc5-11eb-9b33-235275e275a3.png)

**Comment by mivu-odoo** [comment]
Hello!

I opened PR #2008 to address this issue. Thank you for catching it!
